[project]
src = "src"
out = "out"
dot_env = ".env"

[networks.robinhood]
url = "https://rpc.mainnet.chain.robinhood.com"
chain_id = 4663
prompt_live = true
explorer_uri = "https://robinhoodchain.blockscout.com"
explorer_type = "blockscout"
